### ISSUE TITLE
Linear solvers don't use the `init` argument to warm start solvers.

### ISSUE THREAD

**Issue by GeoffNN** [google/jaxopt#145]
As an example, the `init` argument in `solve_gmres` is not passed to the `x0` argument in `jax.scipy.sparse.linalg.gmres`.

```python
def solve_gmres(matvec: Callable,
                b: Any,
                ridge: Optional[float] = None,
                init: Optional[Any] = None,
                tol: float = 1e-5,
                **kwargs) -> Any:
  """Solves ``A x = b`` using gmres.
  Args:
    matvec: product between ``A`` and a vector.
    b: pytree.
    ridge: optional ridge regularization.
    init: optional initialization to be used by gmres.
    **kwargs: additional keyword arguments for solver.
  Returns:
    pytree with same structure as ``b``.
  """
  if ridge is not None:
    matvec = _make_ridge_matvec(matvec, ridge=ridge)
  return jax.scipy.sparse.linalg.gmres(matvec, b, tol=tol, **kwargs)[0]
```

I can take care of this soon.

**Comment by mblondel** [comment]
Indeed, good catch. We need to set `x0=init` in the `gmres` call. Also I'm not sure if forwarding the kwargs is a good idea in the end. This could lead to us breaking user code if we make changes to argument names...

**Comment by GeoffNN** [comment]
That's true... Should we explicitly call the arguments from the underlying solvers in `jax.scipy.sparse.linalg` ? The main point of these wrappers is to add the `ridge` argument... Perhaps we should add this directly in the underlying solvers?

**Comment by mblondel** [comment]
I guess one of my early motivations was to have matvec support even for direct linear solvers (by materializing the matrix in memory).
