### ISSUE TITLE
`solver.init` -> `solver.init_state` is an undocumented breaking change

### ISSUE THREAD

**Issue by phinate** [google/jaxopt#154]
When running old code that used `jaxopt==0.1`, I found that it no longer runs due to the paradigm shift of

`params, state = solver.init(...)` --> `state = solver.init_state(...)`

but could not find this in the release notes or documentation. Would be nice to have this written down somewhere just in case people prototyped with early `jaxopt` releases.

**Comment by mblondel** [comment]
We had a deprecation warning that we [removed](https://github.com/google/jaxopt/commit/724fdbff8ab014fa0214d6d0213d1046f410f8e6#diff-c3410633be35593332247ffc9385b2746f8ba19c371ac000c8ac387f27813b6fL120) but maybe we should have kept it a bit longer. I can add a small note on this in the [changelog](https://jaxopt.github.io/stable/changelog.html) if you think that's useful.

**Comment by phinate** [comment]
I see, I did feel like perhaps I’d seen it before. Just wanted to flag to make sure — amending the changelog sounds great, thanks :)
