### ISSUE TITLE
Bound constraints in LBFGS

### ISSUE THREAD

**Issue by ianwilliamson** [google/jaxopt#173]
This is a great package! Are bound constraints for LBFGS on the roadmap?

**Comment by mblondel** [comment]
Yes, though it make take a while. In the meantime, you can use the wrapper [jaxopt.ScipyBoundedMinimize](https://jaxopt.github.io/stable/constrained.html#box-constraints).

**Comment by ianwilliamson** [comment]
> Yes, though it make take a while. In the meantime, you can use the wrapper [jaxopt.ScipyBoundedMinimize](https://jaxopt.github.io/stable/constrained.html#box-constraints).

Thank you! I totally missed that in the documentation.

**Comment by mblondel** [comment]
And also [jaxopt.ProjectedGradient](https://jaxopt.github.io/stable/constrained.html) together with `projection_box`.

**Comment by nikithiel** [comment]
Is this still unresolved or is it possible to use bounds with `jaxopt.LBFGS` now? In the documentation I saw, that `.init_state` and `.update()` accepts `bounds `as input.

**Comment by mblondel** [comment]
Indeed you can now use `jaxopt.LBFGSB`. The `bounds` are to be passed to `run` if you let jaxopt do the optimization loop or to `init_state` and `update` if you want to do the optimization loop manually. I will close this issue then.
