### ISSUE TITLE
feature request: make examples gallery runnable in colab

### ISSUE THREAD

**Issue by murphyk** [google/jaxopt#199]
There are lots of cool examples in the gallery, but it is not always clear what output they should produce (eg this [sparse coding](https://jaxopt.github.io/stable/auto_examples/implicit_diff/sparse_coding.html) example). It would be great to show the output, and even better if I could click a button and run it in colab. For example, the notebook might be something like this:
```
%pip install jaxopt
from jaxopt.examples.implicit_diff import sparse_coding as demo

# wrapper around FLAGS so we can call main() from colab
import argparse
parser = argparse.ArgumentParser(description='My Demo')
parser.add_argument("-arg1", default=1, type=int,  help="An integer to print")
...
#args = parser.parse_args() # error in colab
args, unused = parser.parse_known_args()
args.arg1 = 42

demo.main(args)
```

**Comment by fabianp** [comment]
Thanks @murphyk for the suggestion!

We're migrating all the examples to a notebook format, where they have a are colab-runnable button, first example [here](https://github.com/google/jaxopt/blob/main/docs/notebooks/deep_learning/resnet_flax.ipynb)
