### ISSUE TITLE
missing documentation for LM and Gauss-Newton

### ISSUE THREAD

**Issue by murphyk** [google/jaxopt#200]
On the page https://jaxopt.github.io/stable/unconstrained.html, the following new solvers are not listed:
- https://github.com/google/jaxopt/blob/main/jaxopt/_src/levenberg_marquardt.py
- https://github.com/google/jaxopt/blob/main/jaxopt/_src/gauss_newton.py

**Comment by mblondel** [comment]
Thanks for reporting! This is on @amir-saadat's todo list. The plan is to add a "Nonlinear least squares" chapter to the documentation.

**Comment by mblondel** [comment]
Done: https://jaxopt.github.io/stable/nonlinear_least_squares.html

**Comment by murphyk** [comment]
Thanks. But the term `h_{gn}` is not defined.

**Comment by mblondel** [comment]
I agree that this part is a bit unclear @amir-saadat
