### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by JeppeKlitgaard** [google/jaxopt#213]
As far as I can tell, Python 3.10 is supported by `jaxopt`, but it would be nice for this to be made 'official'.

As far as I can tell, the only changes required would be:
- [ ] Add Python 3.10 CI testing
- [ ] Add `Programming Language :: Python :: 3.10` classifier to `setup.py`

**Comment by fabianp** [comment]
Sounds good to me. Would you be willing to submit a pull request with these items @JeppeKlitgaard ?

**Comment by JeppeKlitgaard** [comment]
Absolutely. Are there any spots I have missed that need updating?
