### ISSUE TITLE
Unexpected TypeError in LBFGS

### ISSUE THREAD

**Issue by fabianp** [google/jaxopt#223]
I have the following code that I would expect to work both with GradientDescent and LBFGS, but the LBFGS one fails:

```
# this works
x0 = jnp.zeros(n_features)
solver = jaxopt.GradientDescent(loss)
solver.run(x0, A, b, lmbda)

# this doesn't works
x0 = jnp.zeros(n_features)
solver = jaxopt.LBFGS(loss)
solver.run(x0, A, b, lmbda)
```

This was unexpected, as according to the documentation solver.run has the same API in both cases. Here is the full notebook: https://gist.github.com/fabianp/6c3250512778e0612cbc49a60e32ff00

**Comment by mblondel** [comment]
Fixed in #239
