### ISSUE TITLE
Small issues in the documentation

### ISSUE THREAD

**Issue by mblondel** [google/jaxopt#237]
- The adversarial notebook contains a KeyboardInterrupt (https://jaxopt.github.io/stable/notebooks/deep_learning/adversarial_training.html)
- Link to resnet example is broken https://jaxopt.github.io/stable/stochastic.html

**Comment by fabianp** [comment]
strangely the notebook on github doesn't have the keyboardinterrupt: https://github.com/google/jaxopt/blob/main/docs/notebooks/deep_learning/adversarial_training.ipynb

**Comment by fabianp** [comment]
I believe this has now been resolved
