### ISSUE TITLE
Include JAX's pylintrc file

### ISSUE THREAD

**Issue by fabianp** [google/jaxopt#355]
I find it useful to use a python linter on the project, but these usually don't come by default with Google's python style. JAX for example includes a pylintrc file in the top level so that all devs  have the same config: https://github.com/google/jax/blob/main/pylintrc

I propose we do the same and include this file in JAXopt. Thoughts?

**Comment by NeilGirdhar** [comment]
Since the setup and requirements are fairly simple, you may also want to consider putting everything (requirements.txt, setup.py, pylintrc) into a pyproject.toml file.
