### ISSUE TITLE
Passing bounds to the ScipyMinimize wrapper?

### ISSUE THREAD

**Issue by lcgordon** [google/jaxopt#388]
Hi! I'm trying to use ScipyMinimize() with the bounds keyword. It looks like passing bounds using the jaxopt wrapper is implemented in the class in the private _run() method (lines 302-303 in jaxopt/_src/scipy_wrappers.py) but the public run() automatically passes bounds=None to _run() (line 334).  Is this an issue of just needing to edit run() to allow bounds or is there another reason that this was disabled?

**Comment by mblondel** [comment]
You need to use `ScipyBoundedMinimize` instead.

https://jaxopt.github.io/stable/constrained.html#box-constraints
