### ISSUE TITLE
Static parameters within a pytree

### ISSUE THREAD

**Issue by hkortier** [google/jaxopt#392]
Is it possible to set certain parameters of a pytree as being static?

**Comment by mblondel** [comment]
You mean that you don't want to optimize some parameters? No, we don't support that directly. You need to separate the pytree into two parts and express your function like this:
```python
def fun(pytree_var):
  return fun_full(pytree_var, pytree_const)
```
where `pytree_var` is the variable part and `pytree_const` is the part you want to keep fixed.
