### ISSUE TITLE
Potentially make matplotlib an optional dependency

### ISSUE THREAD

**Issue by ntenenz** [google/jaxopt#396]
Apologies in advance for quoting, nearly verbatim, this [issue](https://github.com/ott-jax/ott/issues/292) from the ott-jax package but the issue is largely identical. 

matplotlib is a fairly "heavy" dependency in that it pulls in lots of extra packages. Unsurprisingly, it's not truly required to use the bulk of jaxopt outside of running some examples / benchmarks. I'm wondering whether the team would consider making matplotlib an optional dependency to minimize the number of packages pulled in by downstream projects.

**Comment by mblondel** [comment]
+1, see #397 for a fix

**Comment by mblondel** [comment]
Fixed by #397
