### ISSUE TITLE
Implicit Differentiation with jaxopt.ScipyMinimize

### ISSUE THREAD

**Issue by Wenlin-Chen** [google/jaxopt#406]
Hi! There is no `implicit_diff` argument in  `jaxopt.ScipyMinimize`. Does this mean that `jaxopt.ScipyMinimize` only supports implicit differentiation but not autodiff of unrolled iterations? Thanks!

**Comment by mblondel** [comment]
Yes exactly, because it’s a black box function we cannot unroll it.

Le mar. 21 févr. 2023 à 01:41, Wenlin Chen ***@***.***> a
écrit :
