### ISSUE TITLE
LBFGSB returns parameters outside of bounds

### ISSUE THREAD

**Issue by javier-garcia-tilburg** [google/jaxopt#439]
The algorithm `jaxopt.LBFGSB` sometimes returns parameters outside of the specified bounds.

```python
solver = LBFGSB(fun=objective_fn, jit=True, tol=1e-3,)

n_params = 41

res = solver.run(
    init_params=jnp.repeat(0.01, n_params),
    bounds=(jnp.repeat(0, n_params), jnp.repeat(1, n_params)),
    ...
)

print(res.params)

if any(res.params > 1):
    raise Exception("Parameters outside of bounds")
```

If you are interested in a minimal example to reproduce the bug, I can share it in private. Just tell me where to upload or send the file (~250 lines of code).

**Comment by mblondel** [comment]
CC @srvasude @emilyfertig

**Comment by emilyfertig** [comment]
Thanks for the report @javier-garcia-tilburg ! Is it significantly outside the bounds or only barely, such that it could be a numerics issue?

If it's not a numerics issue, I suspect it could be because zoom linesearch, the default, doesn't apply a max stepsize. L-BFGS-B has a default max stepsize of 1 for the linesearch, which is passed to the other linesearch methods and would keep the result in bounds. Could you try it with `linesearch='hager-zhang'` and `linesearch='backtracking'` and see if it has the same issue? (And if it's not too much trouble could you look at the step size returned by `zoom_linesearch` in your problem and confirm that it's > 1.?)

**Comment by javier-garcia-tilburg** [comment]
@emilyfertig 

> Is it significantly outside the bounds or only barely, such that it could be a numerics issue?

I think it is significant; the boundaries are `(0,1)` and LBFGSB returns parameters close to `1.5`. The minimal reproduction example produces a `1.11`.

>  I suspect it could be because zoom linesearch [...] Could you try it with linesearch='hager-zhang' and linesearch='backtracking' and see if it has the same issue?

You are right, I'm using the default linesearch method, zoom. Regarding the other methods, `backtracking` does respect boundaries, but `hager-zhang` did not terminate in 29+ hours so I gave up.

> could you look at the step size returned by zoom_linesearch in your problem and confirm that it's > 1.?

The information returned by `.run()` says that the (last?) step size is `1.0`. During the optimization process, the variable `new_stepsize` seems to be `1.0` in about 95% of `.update()` calls, and `2.0` in the remaining 5%. 

The variable `new_stepsize` was measured by adding a debug print after the following line.

https://github.com/google/jaxopt/blob/d40b6d736aca6366af6816c9f16498a594850300/jaxopt/_src/lbfgsb.py#L500

```python
 jax.debug.print("new_stepsize {new_stepsize}", new_stepsize=new_stepsize)
```

**Comment by javier-garcia-tilburg** [comment]
Using `max_stepsize=1` does not work, LBFGSB still returns values outside of bounds.

**Comment by emilyfertig** [comment]
Thanks, I'll work on a fix.

@javier-garcia-tilburg are you synced past d40b6d736aca6366af6816c9f16498a594850300? I would have expected that to fix the issue with Hager-Zhang not terminating.

**Comment by kallel-mahdi** [comment]
Hi, thank you for the amazing effort put into this library.

For your information. Although i am using the current developement version, I am getting parameters that are out of bounds using LBFGS-B + Hager Zhang line search.

**Comment by vroulet** [comment]
Hello!

We have reimplemented the zoom linesearch to take a max_stepsize. Could you pull the most recent version and see if it still does not work? If not, could you send us a reproducible code such that we can investigate that a bit better?

**Comment by javier-garcia-tilburg** [comment]
@vroulet , I just tried the new version and I the problem is gone. The solution returned by LBFGSB is within bounds whether I leave `max_stepsize=1` or not.

Thank you for your work and effort
