### ISSUE TITLE
tree_util.tree_vdot bugging on example. 

### ISSUE THREAD

**Issue by gowerrobert** [google/jaxopt#44]
https://github.com/google/jaxopt/blob/1d553785f1755249d0e546c174619a0e70e17b7e/jaxopt/_src/tree_util.py#L51

See [this colab](https://colab.research.google.com/drive/1m_eYcxYvCbjVOiHbOHDHzB-KuqBknzHD#scrollTo=4DZ3YA_T2tkz) for details on bug and fix. 

Here's a minimal example to reproduce the bug:

```python
from jaxopt import tree_util
a =(1.0, {"k1": 1.0, "k2": (1.0, 1.0)}, 1.0)
x =(1.0, {"k1": 2.0, "k2": (3.0, 4.0)}, 5.0)
out = tree_util.tree_vdot(a,x)
```

The issue is caused by unexpected behaviour of ```Jax.tree_util.tree_multimap```.  

One way to fix this is to broadcast a product with tree_multimap, and then reduce using the sum
```python

def tree_vdot(tree_x, tree_y):
  """Compute the inner product <tree_x, tree_y>."""
  prod_pair = tu.tree_multimap(lambda x, y: x*y, tree_x, tree_y)
  sums = tu.tree_map(jnp.sum, prod_pair)
  return tu.tree_reduce(operator.add, sums)
```
 I would be happy to implement this fix, implement new accompanying unit test, and make a pull request. More details here

**Comment by mblondel** [comment]
Thanks Robert! The issue comes from the fact that `jnp.vdot` doesn't work between scalars. So this would be another fix:
```python
import functools

_vdot = functools.partial(jnp.vdot, precision=jax.lax.Precision.HIGHEST)

def _vdot_safe(a, b):
  return _vdot(jnp.asarray(a), jnp.asarray(b))

def tree_vdot(tree_x, tree_y):
  """Compute the inner product <tree_x, tree_y>."""
  vdots = tu.tree_multimap(_vdot_safe, tree_x, tree_y)
  return tu.tree_reduce(operator.add, vdots)
  ```

CC @shoyer @froystig

**Comment by gowerrobert** [comment]
Nice solution! I timed the two solutions here in [colab](https://colab.research.google.com/drive/1m_eYcxYvCbjVOiHbOHDHzB-KuqBknzHD#scrollTo=-RYvwLpkQKlV). 

They are pretty much as fast as eachother. So I'd recommend the one you prefer for maintenance/elegance.
