### ISSUE TITLE
AndersonAcceleration mismatch between code and documentation

### ISSUE THREAD

**Issue by lpxhonneux** [google/jaxopt#443]
The documentation at https://jaxopt.github.io/stable/_autosummary/jaxopt.AndersonAcceleration.html#jaxopt.AndersonAcceleration states in the detailed description of parameters that is has an init value `has_aux` but doesn't in the code and naturally fails when one tries to set has_aux at initialisation.

Would it be possible to add the has_aux flag to the AndersonAcceleration?

**Comment by Algue-Rythme** [comment]
Hi Sophie
Nice catch, we will solve that!
