### ISSUE TITLE
website - defining an objective function

### ISSUE THREAD

**Issue by pharringtonp19** [google/jaxopt#48]
I am really enjoying the [website](https://jaxopt.github.io/stable/) - very helpful!

I noticed that in the [section](https://jaxopt.github.io/stable/unconstrained.html) regarding how to define an objective function, the code switches between referring to the weights of the model as `params` and `w`

**Comment by mblondel** [comment]
Maybe it wasn't super clear but for some objectives `params = W` (the weights) and for others `params = (W, b)` (the weights and the intercept). Anything we can improve?

**Comment by pharringtonp19** [comment]
@mblondel I see, thanks
