### ISSUE TITLE
name 'signature' is not defined

### ISSUE THREAD

**Issue by pharringtonp19** [google/jaxopt#51]
I get the following error "JaxStackTraceBeforeTransformation: NameError: name 'signature' is not defined" 
 with the following example when I set `implicit_diff=True`, but it works when I set `implicit_diff=False`

```
import jaxopt
import jax 
import jax.numpy as jnp 
import matplotlib.pyplot as plt 
jax.config.update("jax_enable_x64", True)

X = jax.random.normal(jax.random.PRNGKey(1), (100, 10))
y =  jax.random.normal(jax.random.PRNGKey(2), (100, 1))

def ridge_reg_objective(params, l2reg, X, y):
  residuals = jnp.dot(X, params) - y
  return jnp.mean(residuals ** 2) + l2reg*jnp.linalg.norm(params)

def ridge_reg_solution(l2reg, X, y):
  gd = jaxopt.GradientDescent(fun=ridge_reg_objective, maxiter=500, implicit_diff=False)
  return gd.run(init_params, l2reg=l2reg, X=X, y=y).params

l2reg = 0.01
init_params = jax.random.normal(jax.random.PRNGKey(0), shape=(X.shape[1],))
print(jax.jacobian(ridge_reg_solution, argnums=0)(l2reg, X, y))
```

**Comment by pharringtonp19** [comment]
The issue appears to be solved by fllinares in [this issue](https://github.com/google/jaxopt/issues/31).  He says there that we shouldn't include keyword arguments in the call to `solver.run`

@mblondel Would it be possible to include keyword arguments in the call to `solver.run`?

**Comment by mblondel** [comment]
Ok I confirm that replacing keyword arguments

`return gd.run(init_params, l2reg=l2reg, X=X, y=y).params`

with positional arguments

`return gd.run(init_params, l2reg, X, y).params`

works. PR #34 was supposed to fix this but it seems like it's not entirely fixed yet. 

CC @froystig

**Comment by mblondel** [comment]
Essentially, we need to make [this line](https://github.com/google/jaxopt/blob/main/tests/implicit_diff_test.py#L145) work even if keyword arguments are used.
