### ISSUE TITLE
Does jaxopt.LBFGS required double precision?

### ISSUE THREAD

**Issue by joacorapela** [google/jaxopt#608]
The PyTorch implementation of LBFGS requires double precision (please refer to this [issue](https://github.com/pytorch/pytorch/issues/49993)).

[jaxopt.ScipyMinimize](https://jaxopt.github.io/stable/_autosummary/jaxopt.ScipyMinimize.html) uses double precision by default.

Does [jaxopt.LBFGS](https://jaxopt.github.io/stable/unconstrained.html) require double precision?

**Comment by mblondel** [comment]
No it uses the same precision as the parameters.

**Comment by joacorapela** [comment]
Thanks Mathieu. 

[jaxopt.ScipyMinimize](https://jaxopt.github.io/stable/_autosummary/jaxopt.ScipyMinimize.html) says:

> Note that some methods relying on FORTRAN code, such as the L-BFGS-B solver for scipy.optimize.minimize, require casting to float64.

Can I assume that this does not hold for [jaxopt.LBFGS](https://jaxopt.github.io/stable/unconstrained.html) and that there should not be very large differences in the result of a [jaxopt.LBFGS](https://jaxopt.github.io/stable/unconstrained.html) optimization if I use simple or double precision parameters?

**Comment by mblondel** [comment]
* `jaxopt.ScipyMinimize` is a wrapper around SciPy, which uses a FORTRAN implementation for LBFGS-B. The FORTRAN code uses double precision.
* `jaxopt.LBFGS` is a pure implementation in JAX, which supports any dtype.

**Comment by joacorapela** [comment]
Thanks @mblondel

**Comment by joacorapela** [comment]
Thanks @mblondel
